In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size="6" color="red"> ch10. N차원배열(Numby 배열) 다루기 </font></b>

# 4절. 복사와 뷰

## 4.1 할당

In [3]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = a

In [5]:
a.shape, a.ndim, id(a), type(a)

((12,), 1, 1951202654512, numpy.ndarray)

In [7]:
b.shape, b.ndim, id(b), type(b)

((12,), 1, 1951202654512, numpy.ndarray)

In [8]:
a is b

True

In [9]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [11]:
np.all(a==b)

True

In [12]:
b.shape = (3,4) # 할당받은 b의 shape을 수정

In [13]:
a.shape, a.ndim, id(a), type(a)

((3, 4), 2, 1951202654512, numpy.ndarray)

In [14]:
b.shape, b.ndim, id(b), type(b)

((3, 4), 2, 1951202654512, numpy.ndarray)

## 4.2 얕은 복사 : 뷰(View)

In [16]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
# 얕은 복사는 틀을 복사하는것. 원래 깊은복사는 a의 1,2,3,4,5,6,7,8,9,10,11 과 행열까지 다 복사하고, 얕은복사는 데이터는 그대로, 행열의 형식만 변경하는 것.

c = a.view()
print(id(a), id(c))

1951256881136 1951256882480


In [18]:
c == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
# a와 c의 0번째 방에는 0이 들어있는데 c의 0번재 값을 바꾸면 a의 값도 바뀜. 그러나 틀만 바꾸는건 c만 바뀜.

c.shape = (2,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
c[1, ::2] = [9,9,9] # 1행의 짝수번째 열 변경(9)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 9,  7,  9,  9,  9, 11]])

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  9,  7],
       [ 9,  9,  9, 11]])

## 4.3 깊은복사

In [32]:
a = np.array([[5, 4, 13, 0],
             [99, 6, 16, 1],
             [20, 5, 14, 0]])
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

In [33]:
# 독립변수 추출
# 변수를 x소문자가 아니라 X대문자로 쓰는 이유는 독립변수의 가짓수가 여러개일때 대문자 사용

# X = a[:, :-1] # 슬라이싱이 될 때, 뷰가 반환됨(얕은복사)
X = a[:, :-1].copy() # 깊은복사
# X = np.array(a[:, :-1], copy = True) 깊은복사지만 이렇게 안씀
X

array([[ 5,  4, 13],
       [99,  6, 16],
       [20,  5, 14]])

In [34]:
X[:, 0] = -9
X

array([[-9,  4, 13],
       [-9,  6, 16],
       [-9,  5, 14]])

In [35]:
a

array([[ 5,  4, 13,  0],
       [99,  6, 16,  1],
       [20,  5, 14,  0]])

# 5절. 고급인덱싱